### ISSUE TITLE
youku无法下载

### ISSUE THREAD

**Issue by syazyz** [soimort/you-get#2284]
Please make sure these boxes are checked before submitting your issue – thank you!

- [check] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [check] Your `you-get` is up-to-date.
- [check] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [check] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [check] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
 you-get http://v.youku.com/v_show/id_XMjk3Njc4NDY0NA==.html?spm=a2hzp.8253869.0.0 --debug
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjk3Njc4NDY0NA==&ccode=0401&client_ip=192.168.1.1&utid=T68cEv0/hwkCAbSMsFCqVP5Y&client_ts=1502986576
site:                优酷 (Youku)
title:               20170817晚上effort 司马懿点播火星vs上帝BO3 好久没看到这两人的对决(司马懿 电小柱解说)
stream:
    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          202.5 MiB (212346919 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjk3Njc4NDY0NA%3D%3D&type=mp4&ups_client_netip=180.140.176.80&ups_ts=1502986576&utid=T68cEv0%2FhwkCAbSMsFCqVP5Y&ccode=0401&psid=124628f4f5bc7ffa8527f52191936357&duration=3195&expire=18000&ups_key=7eca429fbf2e697d399477515975157b
    # download-with: you-get --format=mp4 [URL]

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading 20170817晚上effort 司马懿点播火星vs上帝BO3 好久没看到这两人的对决(司马懿 电小柱解说).mp4 ...
 0.0% (  0.0/202.5MB) ├─────────────────────────────────────────┤[1/9] [DEBUG] HTTP Error with code403
[DEBUG] HTTP Error with code403
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjk3Njc4NDY0NA==.html?spm=a2hzp.8253869.0.0']
Traceback (most recent call last):
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.803', 'console_scripts', 'you-get')()
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\common.py", line 1360, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\common.py", line 1267, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\common.py", line 1065, in download_main
    download(url, **kwargs)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\common.py", line 1353, in any_download
    m.download(url, **kwargs)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\extractors\youku.py", line 277, in youku_download_by_url
    Youku().download_by_url(url, **kwargs)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\extractor.py", line 227, in download
    av=stream_id in self.dash_streams)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\common.py", line 790, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers, **kwargs)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\common.py", line 531, in url_save
    file_size = url_size(url, faker=faker, headers=tmp_headers)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\common.py", line 437, in url_size
    size = response.headers['content-length']
AttributeError: 'NoneType' object has no attribute 'headers'
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by soimort** [comment]
AFAIK this is a regression caused by 58f778e.

(Relying on a specific CDN is not a good idea and it could break things.)

**Comment by rosynirvana** [comment]
should be fixed with https://github.com/soimort/you-get/commit/170d7f0c24aff6da490514b1a0e85e8edbc4a35b if you're using the develop branch

I thought the urls which startswith ```k.youku.com``` are gone but they aren't

urls startswith an IP addr are causing troubles. Kicking them back to the dispatcher seems better.

**Comment by lki2019** [comment]
rame=14383 fps=0.0 q=-1.0 size=   37376kB time=00:09:35.24 bitrate= 532.3kbits/
rame=28230 fps=28228 q=-1.0 size=   88064kB time=00:18:49.12 bitrate= 638.9kbit
rame=42450 fps=28298 q=-1.0 size=  133120kB time=00:28:17.92 bitrate= 642.3kbit
rame=57789 fps=28893 q=-1.0 size=  172288kB time=00:38:31.48 bitrate= 610.6kbit
rame=71415 fps=28564 q=-1.0 size=  191488kB time=00:47:36.52 bitrate= 549.2kbit
rame=75904 fps=24967 q=-1.0 size=  198912kB time=00:50:36.08 bitrate= 536.7kbit
rame=79754 fps=21909 q=-1.0 size=  205056kB time=00:53:10.08 bitrate= 526.6kbit
rame=79883 fps=20269 q=-1.0 Lsize=  208098kB time=00:53:15.25 bitrate= 533.5kbi
s/s speed= 811x
ideo:180290kB audio:24964kB subtitle:0kB other streams:0kB global headers:0kB m
xing overhead: 1.385625%
erged into 20170817晚上effort 司马懿点播火星vs上帝BO3 好久没看到这两人的对决(司
马懿 电小柱解说).mp4


我这里没什么问题

**Comment by syazyz** [comment]
升级develop branch后解决
